### ISSUE TITLE
VS Code and Atom are not "lightweight"

### ISSUE THREAD

**Issue by shlomif** [niem94/my-software-engineer-list#2]
Hi!

Thanks for maintaining this page.

See https://www.reddit.com/r/programming/comments/73vua5/benchmarks_showing_electron_apps_are_super_slow/ and https://www.shlomifish.org/humour/bits/Atom-Text-Editor-edits-2_000_001-bytes/ . 

Moreover, saying they are "Owned" by MS / GitHub is misleading because they are under https://en.wikipedia.org/wiki/Permissive_software_licence -s and can be forked. "originate" is more accurate.

Please correct these issues.

**Comment by niem94** [comment]
Thank you a lot for the feedback!
I removed the word "light-weight" from both, and added that they are electron based. I then reworded "owned" to "originated from". Please do tell, if you find something else missing or wrong :-)

**Comment by shlomif** [comment]
@niem94 : thanks!
